Repository RMeli/spyrmsd, pull requests merged in 2024-06, with the labels that each got.

#129 Add dependabot
  .github/dependabot.yaml
Labels: enhancement, ci

#131 Add --version command to CLI and add -dev to develop version
  CHANGELOG.md
  setup.py
  spyrmsd/__init__.py
  spyrmsd/__main__.py
Labels: enhancement, release

#113 RMSD with multicore and timeout functionality
  CHANGELOG.md
  devtools/conda-envs/spyrmsd-test-rdkit-all.yaml
  devtools/conda-envs/spyrmsd-test-rdkit-nogt.yaml
  spyrmsd/parallel.py
  spyrmsd/rmsd.py
  tests/conftest.py
  tests/data/molecules/muparfostat.sdf
  tests/test_parallel.py
Labels: enhancement
