Repository RMeli/spyrmsd, pull requests merged in 2024-03, with the labels that each got.

#107 Add functionality to select backend
  .github/workflows/pytest.yml
  .pre-commit-config.yaml
  CHANGELOG.md
  CITATION.cff
  devtools/conda-envs/spyrmsd-test-rdkit-all.yaml
  spyrmsd/__init__.py
  spyrmsd/graph.py
  spyrmsd/molecule.py
  tests/test_graph.py
  tests/test_molecule.py
Labels: enhancement

#112 Documentation and CLI for backend selection
  CHANGELOG.md
  README.md
  docs/source/tutorials/tutorial.ipynb
  docs/source/tutorials/tutorial.rst
  spyrmsd/__main__.py
  spyrmsd/graph.py
  tests/test_graph.py
  tests/test_molecule.py
Labels: documentation, enhancement, cleanup

#114 Update .readthedocs.yml
  .readthedocs.yml
Labels: documentation, problem
